import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import test from 'node:test'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(here, '../../../..')
const read = (relative) => fs.readFileSync(path.join(root, relative), 'utf8')

const instructionalSql = read('supabase/migrations/20260909010000_harden_instructional_session_ownership.sql')
const continuitySql = read('supabase/migrations/20260916134000_preserve_instructional_continuity.sql')
const goldenSql = read('supabase/migrations/20260909011000_harden_golden_key_lifecycle.sql')
const trackingHook = read('src/app/hooks/useSessionTracking.js')
const trackingClient = read('src/app/lib/sessionTracking.js')
const sessionPage = read('src/app/session/v2/SessionPageV2.jsx')
const snapshotRoute = read('src/app/api/snapshots/route.js')
const snapshotService = read('src/app/session/v2/SnapshotService.jsx')
const evidenceRoute = read('src/app/api/evidence/route.js')
const webbPage = read('src/app/session/webb/page.jsx')
const learnerHome = read('src/app/learn/LearnerHome.js')
const learnerApi = read('src/app/facilitator/learners/clientApi.js')
const takeoverDialog = read('src/app/session/components/SessionTakeoverDialog.jsx')
const capacityModule = read('src/app/lib/syllabus/capacity.mjs')
const executionStartRoute = read('src/app/api/syllabus/execution/start/route.js')
const executionCompleteRoute = read('src/app/api/syllabus/execution/complete/route.js')

test('instructional execution ownership keeps historical end reasons but no longer auto-expires a foreign browser', () => {
  assert.match(instructionalSql, /ended_reason is null or ended_reason in \('completed', 'moved', 'taken_over', 'expired', 'released'\)/)
  assert.doesNotMatch(continuitySql, /v_lease_cutoff/)
  assert.doesNotMatch(continuitySql, /ended_reason = 'expired'/)
  assert.match(continuitySql, /Foreign browser ownership never expires implicitly/)
  assert.match(continuitySql, /p_expected_conflicting_session_id <> v_conflicting_active\.id/)
  assert.match(continuitySql, /when v_takeover and session_id <> p_browser_session_id then 'taken_over'\s+else 'moved'/)
  assert.match(continuitySql, /create table if not exists public\.lesson_snapshot_handoffs/)
  assert.match(continuitySql, /continuation_of_session_id/)
  assert.match(continuitySql, /v_resume_from public\.lesson_sessions%rowtype/)
  assert.match(continuitySql, /v_resume_found/)
  assert.match(continuitySql, /s\.ended_reason in \('expired', 'moved', 'released'\)/)
  assert.match(continuitySql, /'resume_after_' \|\| coalesce\(v_resume_from\.ended_reason, 'interruption'\)/)
  assert.match(continuitySql, /snapshotHandoffId/)
  assert.match(continuitySql, /ownership_continuation/)
  assert.match(instructionalSql, /create or replace function public\.heartbeat_lesson_session/)
  assert.match(continuitySql, /ended_reason = 'completed'/)
})

test('instructional watcher renews exact ownership and only takeover opens takeover UI', () => {
  assert.match(trackingClient, /fetch\('\/api\/syllabus\/execution\/heartbeat'/)
  assert.match(trackingClient, /JSON\.stringify\(\{ sessionId, learnerId, browserSessionId \}\)/)
  assert.match(trackingHook, /setInterval\(heartbeat, 15000\)/)
  assert.match(trackingHook, /if \(reason === 'taken_over'\)/)
  assert.match(trackingHook, /onSessionTakenOver/)
  assert.match(trackingHook, /onSessionEnded/)
  assert.match(sessionPage, /if \(!normalized \|\| normalized === 'completed'\) return;/)
  assert.match(sessionPage, /snapshotServiceRef\.current\?\.fenceWrites/)
  assert.match(sessionPage, /timerServiceRef\.current\?\.pause/)
  assert.match(sessionPage, /audioEngineRef\.current\?\.stop/)
  assert.match(sessionPage, /orchestratorRef\.current\?\.destroy/)
})

test('shared snapshots and educational evidence reject writes from a losing execution owner', () => {
  assert.match(snapshotRoute, /verifySnapshotExecutionOwner/)
  assert.match(snapshotRoute, /executionSessionId/)
  assert.match(snapshotRoute, /browserSessionId/)
  assert.match(snapshotRoute, /code: 'SNAPSHOT_OWNERSHIP_LOST'/)
  assert.match(snapshotRoute, /status: 409/)
  assert.match(snapshotService, /bindExecutionOwner\(\{ executionSessionId, browserSessionId \} = \{\}\)/)
  assert.match(snapshotService, /fenceWrites\(reason = 'ownership-lost'\)/)
  const fenceBody = snapshotService.match(/fenceWrites\(reason = 'ownership-lost'\) \{([\s\S]*?)\n  \}/)?.[1] || ''
  assert.doesNotMatch(fenceBody, /#snapshot = null|#deleteFromLocalStorage/)
  assert.match(snapshotService, /offerTakeoverSnapshot/)
  assert.match(snapshotService, /claimTakeoverSnapshot/)
  assert.match(snapshotRoute, /handoff_action:?'?\s*source_offer|action === 'source_offer'/)
  assert.match(snapshotRoute, /action === 'target_claim'/)
  assert.match(sessionPage, /pendingSnapshotHandoffRef/)
  assert.match(sessionPage, /Resume lesson here/)
  assert.match(sessionPage, /fetch\('\/api\/syllabus\/execution\/takeover'/)
  assert.match(takeoverDialog, /\^\\d\{4,8\}\$/)
  assert.match(takeoverDialog, /maxLength=\{8\}/)
  assert.match(snapshotService, /if \(this\.#writesFenced\) return \{ success: false, blocked: true, ownershipLost: true \}/)
  assert.match(evidenceRoute, /verifyEvidenceExecutionOwner/)
  assert.match(evidenceRoute, /code: 'EVIDENCE_OWNERSHIP_LOST'/)
})

test('takeover keeps target Snapshot writes fenced until transferred state is adopted', () => {
  const start = sessionPage.indexOf('const handleSessionTakeover = useCallback')
  const end = sessionPage.indexOf('const handleRecoverExecution = useCallback')
  const takeover = sessionPage.slice(start, end)
  const fence = takeover.indexOf("fenceWrites?.('takeover-handoff')")
  const claim = takeover.indexOf('claimTakeoverSnapshot?.', fence)
  const bind = takeover.indexOf('bindExecutionOwner?.', claim)
  assert.ok(fence >= 0 && claim > fence && bind > claim)
})
test('Syllabus capacity stays planning-only and cannot fence or terminate instructional runtime', () => {
  assert.match(capacityModule, /capacity_conflict|daily_capacity|subject_capacity/)
  const runtime = [sessionPage, trackingClient, executionStartRoute, executionCompleteRoute].join('\n')
  assert.doesNotMatch(runtime, /SYLLABUS_CAPACITY_PIN_REQUIRED|capacity_conflict|daily_capacity|subject_capacity/)
})

test('snapshot takeover handoff fails closed instead of inheriting ordinary soft snapshot errors', () => {
  assert.match(snapshotRoute, /SNAPSHOT_HANDOFF_FAILED/)
  assert.match(snapshotRoute, /SNAPSHOT_HANDOFF_UNAVAILABLE/)
  assert.match(snapshotRoute, /return await handleSnapshotHandoff/)
})
test('Mrs. Webb adopts the shared protected session and freezes chat/TTS after ownership loss', () => {
  assert.match(webbPage, /useSessionTracking/)
  assert.match(webbPage, /adoptWebbTrackedSession/)
  assert.match(webbPage, /freezeWebbExecution\('taken_over'\)/)
  assert.match(webbPage, /ttsQueueRef\.current = \[\]/)
  assert.match(webbPage, /ttsCurrentRef\.current\.pause\(\)/)
  assert.match(webbPage, /webbOwnershipEndedReason/)
})

test('Golden Key application and finalization are atomic and completion-idempotent', () => {
  assert.match(goldenSql, /create table if not exists public\.golden_key_session_finalizations/)
  assert.match(goldenSql, /execution_session_id uuid primary key/)
  assert.match(goldenSql, /from public\.learners[\s\S]*for update;/)
  assert.match(goldenSql, /state', 'already_applied'/)
  assert.match(goldenSql, /golden_keys = v_remaining,\s*active_golden_keys = v_active/)
  assert.match(goldenSql, /state', 'already_finalized'/)
  assert.match(goldenSql, /v_session\.ended_reason is distinct from 'completed'/)
  assert.match(goldenSql, /v_active := v_active - v_lesson_key/)
  assert.match(goldenSql, /v_keys := v_keys \+ 1/)
})

test('Golden Key selection does not spend inventory before launch and partial learner updates preserve unrelated mastery targets', () => {
  assert.match(learnerHome, /applyGoldenKeyToLesson\(\{ learnerId, lessonKey: thisLessonKey \}\)/)
  assert.doesNotMatch(learnerHome, /golden_key_pending_lesson/)
  assert.doesNotMatch(learnerHome, /golden_keys:\s*learner\.golden_keys\s*-\s*1/)
  assert.match(sessionPage, /finalizeGoldenKeyForSession/)
  assert.match(sessionPage, /featureState:\s*\{/)
  assert.match(sessionPage, /golden-key-suspended/)
  assert.match(learnerApi, /\.\.\.\(t\.comprehension !== undefined \? \{ comprehension: Number\(t\.comprehension\) \} : \{\}\)/)
  assert.match(learnerApi, /\.\.\.\(updates\.name !== undefined \? \{ name: updates\.name \} : \{\}\)/)
  assert.match(learnerApi, /\.\.\.\(updates\.grade !== undefined \? \{ grade: updates\.grade \} : \{\}\)/)
})
