// Riddles library: 100 short, original-style riddles with clear answers.
// Each item: { id: number, text: string, answer: string }

export const riddles = [
  { id: 1, text: "I have a face but no eyes, hands but no fingers. What am I?", answer: "A clock" },
  { id: 2, text: "What gets wetter the more it dries?", answer: "A towel" },
  { id: 3, text: "I speak without a mouth and hear without ears. What am I?", answer: "An echo" },
  { id: 4, text: "The more you take, the more you leave behind. What are they?", answer: "Footsteps" },
  { id: 5, text: "I’m light as a feather, yet the strongest person can’t hold me for long. What am I?", answer: "Your breath" },
  { id: 6, text: "I have a neck but no head, and I wear a cap. What am I?", answer: "A bottle" },
  { id: 7, text: "What has a head and a tail, but no body?", answer: "A coin" },
  { id: 8, text: "I’m full of holes but can hold water. What am I?", answer: "A sponge" },
  { id: 9, text: "What has keys but can’t open locks?", answer: "A piano" },
  { id: 10, text: "What has many rings but no fingers?", answer: "A tree" },
  { id: 11, text: "I run but never walk, murmur but never talk. What am I?", answer: "A river" },
  { id: 12, text: "What can travel around the world while staying in the same corner?", answer: "A stamp" },
  { id: 13, text: "What belongs to you but is used more by others?", answer: "Your name" },
  { id: 14, text: "I have cities, but no houses; mountains, but no trees; water, but no fish. What am I?", answer: "A map" },
  { id: 15, text: "What has one eye but can’t see?", answer: "A needle" },
  { id: 16, text: "What has to be broken before you can use it?", answer: "An egg" },
  { id: 17, text: "I go up and down but never move. What am I?", answer: "Stairs" },
  { id: 18, text: "I have a bed but never sleep, a mouth but never eat. What am I?", answer: "A river" },
  { id: 19, text: "What can fill a room but takes up no space?", answer: "Light" },
  { id: 20, text: "I shave every day, but my beard stays the same. Who am I?", answer: "A barber" },
  { id: 21, text: "What can you catch but not throw?", answer: "A cold" },
  { id: 22, text: "What has words but never speaks?", answer: "A book" },
  { id: 23, text: "You can drop me from the tallest building and I’ll be fine, but if you drop me in water I die. What am I?", answer: "Paper" },
  { id: 24, text: "I’m always in front of you but can’t be seen. What am I?", answer: "The future" },
  { id: 25, text: "What has many teeth but can’t bite?", answer: "A comb" },
  { id: 26, text: "Where does today come before yesterday?", answer: "The dictionary" },
  { id: 27, text: "What has a thumb and four fingers but isn’t alive?", answer: "A glove" },
  { id: 28, text: "I turn once, what’s out will not get in; turn again, what’s in will not get out. What am I?", answer: "A key" },
  { id: 29, text: "What begins with T, ends with T, and has T in it?", answer: "A teapot" },
  { id: 30, text: "I hide in plain sight at the end of a rainbow. What am I?", answer: "The letter W" },
  { id: 31, text: "I’m always hungry, I must be fed. I touch the wind and soon I’m dead. What am I?", answer: "A fire" },
  { id: 32, text: "What has a spine but no bones?", answer: "A book" },
  { id: 33, text: "I have branches, yet no fruit, trunk, or leaves. What am I?", answer: "A bank" },
  { id: 34, text: "What is so fragile that saying its name breaks it?", answer: "Silence" },
  { id: 35, text: "You see me once in a year, twice in a week, and never in a day. What am I?", answer: "The letter E" },
  { id: 36, text: "I’m long when I’m young and short when I’m old. What am I?", answer: "A candle" },
  { id: 37, text: "What has a tail and no body, is bright but not alive?", answer: "A comet" },
  { id: 38, text: "I fly without wings. I cry without eyes. What am I?", answer: "A cloud" },
  { id: 39, text: "What can run but never walks, has a mouth but never talks, has a head but never weeps, has a bed but never sleeps?", answer: "A river" },
  { id: 40, text: "I am taken from a mine and shut up in a wooden case, from which I am never released, and yet I am used by almost every student. What am I?", answer: "Pencil lead" },
  { id: 41, text: "What room has no doors or windows?", answer: "A mushroom" },
  { id: 42, text: "What invention lets you look right through a wall?", answer: "A window" },
  { id: 43, text: "What goes up but never comes down?", answer: "Your age" },
  { id: 44, text: "I can be cracked, made, told, and played. What am I?", answer: "A joke" },
  { id: 45, text: "I am not alive, yet I grow; I don’t have lungs, yet I need air. What am I?", answer: "A fire" },
  { id: 46, text: "I have a ring, but no finger. What am I?", answer: "A telephone" },
  { id: 47, text: "What can be opened but is never closed?", answer: "An egg" },
  { id: 48, text: "What has 13 hearts but no other organs?", answer: "A deck of cards" },
  { id: 49, text: "What begins with an E and only contains one letter?", answer: "An envelope" },
  { id: 50, text: "I live in winter’s breath and summer’s shade, yet never leave the ground. What am I?", answer: "A shadow" },
  { id: 51, text: "What has a beginning but no end, and an end but no beginning?", answer: "A circle" },
  { id: 52, text: "I am always running but never move. I am always murmuring but never speak. What am I?", answer: "A stream" },
  { id: 53, text: "What kind of band never plays music?", answer: "A rubber band" },
  { id: 54, text: "I arrive by train, I leave by foot, I always keep time. What am I?", answer: "A timetable" },
  { id: 55, text: "I am bought to eat but never eaten. What am I?", answer: "A plate" },
  { id: 56, text: "I’m in seconds, minutes, centuries, and moment, but not in years or days. What am I?", answer: "The letter M" },
  { id: 57, text: "What has four fingers and a thumb but isn’t alive?", answer: "A glove" },
  { id: 58, text: "What kind of coat is best put on wet?", answer: "A coat of paint" },
  { id: 59, text: "I’m seen in the water, but never get wet. What am I?", answer: "A reflection" },
  { id: 60, text: "I have two hands but I can’t clap. What am I?", answer: "A clock" },
  { id: 61, text: "What breaks but never falls, and what falls but never breaks?", answer: "Day breaks and night falls" },
  { id: 62, text: "What can you hold in your right hand but never in your left?", answer: "Your left hand" },
  { id: 63, text: "I’m tall when I’m young, and short when I’m old; I melt but never freeze. What am I?", answer: "A candle" },
  { id: 64, text: "I cross the sky but never leave the ground. What am I?", answer: "A shadow" },
  { id: 65, text: "What begins with P, ends with E, and has thousands of letters?", answer: "The post office" },
  { id: 66, text: "If you have me, you want to share me; if you share me, you no longer have me. What am I?", answer: "A secret" },
  { id: 67, text: "I’m always ahead of you but never seen. What am I?", answer: "Tomorrow" },
  { id: 68, text: "What flies without wings and is lost without a tail?", answer: "A kite" },
  { id: 69, text: "I’m at the end of time and space, but beginning of every end. What am I?", answer: "The letter E" },
  { id: 70, text: "I go all around the world but always stay in a corner. What am I?", answer: "A stamp" },
  { id: 71, text: "What has many needles but doesn’t sew?", answer: "A pine tree" },
  { id: 72, text: "What can you break without touching it?", answer: "A promise" },
  { id: 73, text: "I’m sometimes white and sometimes brown, but always kept up and never let down. What am I?", answer: "A fence" },
  { id: 74, text: "What has to be opened to be eaten, and is wrapped in a shell?", answer: "A nut" },
  { id: 75, text: "I have a tail and a head, no legs, and I’m shiny. What am I?", answer: "A coin" },
  { id: 76, text: "I’m measured in feet but never wear shoes. What am I?", answer: "A ruler" },
  { id: 77, text: "I never ask questions but I’m always answered. What am I?", answer: "A doorbell" },
  { id: 78, text: "I’m always coming but never arrive. What am I?", answer: "Tomorrow" },
  { id: 79, text: "I have four legs but can’t walk. What am I?", answer: "A table" },
  { id: 80, text: "What has a head, a tail, is brown, and has no legs?", answer: "A penny" },
  { id: 81, text: "I can be written, spoken, broken, and exposed. What am I?", answer: "News" },
  { id: 82, text: "I grow when you feed me and die when you water me. What am I?", answer: "A fire" },
  { id: 83, text: "What can you hear but never see and never touch?", answer: "A voice" },
  { id: 84, text: "I point without a finger and move without feet. What am I?", answer: "A compass needle" },
  { id: 85, text: "I’m taken before you get me, and given after you take me. What am I?", answer: "A photograph" },
  { id: 86, text: "I open to close and close to open. What am I?", answer: "An umbrella" },
  { id: 87, text: "What do you answer even though it never asks questions?", answer: "A phone" },
  { id: 88, text: "I’m not alive, but if you don’t feed me I’ll die. What am I?", answer: "A fire" },
  { id: 89, text: "I’m found once in a minute, twice in a moment, and never in a thousand years. What am I?", answer: "The letter M" },
  { id: 90, text: "I have a bed you don’t sleep in and a mouth you don’t eat with. What am I?", answer: "A river" },
  { id: 91, text: "What has bark but no bite and stands in one place?", answer: "A tree" },
  { id: 92, text: "I travel the world while staying put. What am I?", answer: "A postcard or a stamp" },
  { id: 93, text: "I’m there when you need me, gone when you find me. What am I?", answer: "A lost item" },
  { id: 94, text: "I reflect your smile but never laugh. What am I?", answer: "A mirror" },
  { id: 95, text: "I grow up while staying down. What am I?", answer: "A plant" },
  { id: 96, text: "I’m sometimes cracked, sometimes told, sometimes played. What am I?", answer: "A joke" },
  { id: 97, text: "I have layers you can peel, yet I’m not fruit. What am I?", answer: "An onion" },
  { id: 98, text: "I chase the sun but never catch it. What am I?", answer: "A shadow" },
  { id: 99, text: "I make two people out of one. What am I?", answer: "A mirror" },
  { id: 100, text: "I’m the beginning of eternity and the end of time and space. What am I?", answer: "The letter E" },
];

export function pickRandomRiddle() {
  const idx = Math.floor(Math.random() * riddles.length);
  return riddles[idx];
}
